services:
  db:
    image: postgres:17
    container_name: tournament_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: tournament_platform
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: TournamentPlatform.API/Dockerfile
    container_name: tournament_api
    depends_on:
      - db
    ports:
      - "5058:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tournament_platform;Username=postgres;Password=postgres123
      - Jwt__Secret=your-super-secret-key-min-32-characters!!
      - Jwt__Issuer=TournamentPlatform
      - Jwt__Audience=TournamentPlatform
      - Jwt__ExpiryMinutes=60
